version: '3.1'
services:
    angular-service:
      image: angular_container 
      build: 
       context: .
       dockerfile: Dockerfile
      volumes:
        - './:/usr/src/app' 
      ports: 
        - '4200:4200'
      command: bash -c "npm install && npm install --only=dev && npm start"

